# Site settings
title: Alex Bloom | Designer
email: hello@alexbloom.co
author: Alex Bloom
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

facebook-username: alexanderlbloom
twitter-username: alexbloom
instagram-username: alexbloom
dribbble-username: alexbloom
tumblr-username: alexbloom
medium-username: alexbloom
github-username: alexbloom

# Gems
gems:
#  - jekyll-assets
# - autoprefixer-rails

#assets:
#  compress:
#    css: false | true | default - development: false, production: true
#    js: false | true | default - development: false, production: true
#  cache: false | directory | default: .asset-cache
#  prefix: "/assets"
#  assets:
#    - "*.png"
#    - "bundle.css"
#  digest: true
#  sources:
#    - "_assets/folder"

# Build settings
markdown: kramdown

# Exclusions from Build
exclude: [Gemfile, Gemfile.lock nmp-debug, gulpfile, .gitignore, node_modules, gulpfile.js]

