# Site settings
title: Alex Bloom | Designer
email: hello@alexbloom.co
author: Alex Bloom
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

facebook-username: alexanderlbloom
twitter-username: alexbloom
instagram-username: alexbloom
dribbble-username: alexbloom
tumblr-username: alexbloom
medium-username: alexbloom
github-username: alexbloom


# Build settings
markdown: kramdown
